# You can use a Docker image from Docker Hub or your own container registry
image: composer

pipelines:
  default:
    - step:
        script:
          - composer --version
          - composer install
          - vendor/bin/phpunit --version
          - vendor/bin/phpunit