# You can use a Docker image from Docker Hub or your own container registry
image: composer

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - composer --version
          - composer install --ignore-platform-reqs --no-scripts
          - vendor/bin/phpunit --version
          - vendor/bin/phpunit